from datetime import datetime
from html import escape
from typing import Any


def _parse_date(value: Any) -> datetime | None:
    if isinstance(value, datetime):
        return value

    if isinstance(value, str) and value.strip():
        cleaned = value.strip()
        if cleaned.endswith("Z"):
            cleaned = cleaned[:-1] + "+00:00"
        try:
            return datetime.fromisoformat(cleaned)
        except ValueError:
            return None

    return None


def _format_date_label(value: Any, fallback: str) -> str:
    parsed = _parse_date(value)
    if parsed:
        return parsed.strftime("%b %d")
    if isinstance(value, str) and value.strip():
        return value.strip()[:10]
    return fallback


def _safe_score(value: Any) -> float:
    try:
        return max(0.0, min(100.0, float(value)))
    except (TypeError, ValueError):
        return 0.0


def build_progress_graph_svg(
    timeline: list[dict[str, Any]],
    width: int = 960,
    height: int = 420,
) -> str:
    width = max(480, min(width, 1600))
    height = max(280, min(height, 900))

    margin_left = 64
    margin_right = 28
    margin_top = 36
    margin_bottom = 64
    chart_width = width - margin_left - margin_right
    chart_height = height - margin_top - margin_bottom
    chart_bottom = margin_top + chart_height

    latest_score = int(round(_safe_score(timeline[-1].get("confidence_score", 0)))) if timeline else 0

    svg_parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" role="img" aria-label="Confidence progress graph">',
        "<defs>",
        '<linearGradient id="progressFill" x1="0" y1="0" x2="0" y2="1">',
        '<stop offset="0%" stop-color="#3b82f6" stop-opacity="0.35" />',
        '<stop offset="100%" stop-color="#3b82f6" stop-opacity="0.03" />',
        "</linearGradient>",
        "</defs>",
        f'<rect width="{width}" height="{height}" rx="24" fill="#0f172a" />',
        f'<rect x="1" y="1" width="{width - 2}" height="{height - 2}" rx="23" '
        'fill="none" stroke="rgba(148, 163, 184, 0.15)" />',
        '<text x="32" y="34" fill="#f8fafc" font-size="22" font-weight="700" '
        'font-family="Segoe UI, Arial, sans-serif">Confidence Progress</text>',
        '<text x="32" y="56" fill="#94a3b8" font-size="12" font-family="Segoe UI, Arial, sans-serif">'
        "Practice-session trend generated by the backend</text>",
        f'<text x="{width - 32}" y="34" text-anchor="end" fill="#60a5fa" font-size="18" '
        'font-weight="700" font-family="Segoe UI, Arial, sans-serif">'
        f"{latest_score}%</text>",
        f'<text x="{width - 32}" y="56" text-anchor="end" fill="#94a3b8" font-size="12" '
        'font-family="Segoe UI, Arial, sans-serif">'
        f"{len(timeline)} sessions</text>",
    ]

    for tick in range(0, 101, 20):
        y = margin_top + chart_height - (tick / 100) * chart_height
        svg_parts.append(
            f'<line x1="{margin_left}" y1="{y:.2f}" x2="{width - margin_right}" y2="{y:.2f}" '
            'stroke="rgba(148, 163, 184, 0.14)" stroke-width="1" />'
        )
        svg_parts.append(
            f'<text x="{margin_left - 14}" y="{y + 4:.2f}" text-anchor="end" fill="#94a3b8" '
            'font-size="11" font-family="Segoe UI, Arial, sans-serif">'
            f"{tick}</text>"
        )

    if not timeline:
        empty_width = chart_width - 24
        empty_height = chart_height - 24
        svg_parts.extend(
            [
                f'<rect x="{margin_left + 12}" y="{margin_top + 12}" width="{empty_width}" '
                f'height="{empty_height}" rx="18" fill="rgba(15, 23, 42, 0.5)" '
                'stroke="rgba(148, 163, 184, 0.18)" stroke-dasharray="8 8" />',
                f'<text x="{width / 2:.2f}" y="{height / 2 - 8:.2f}" text-anchor="middle" fill="#e2e8f0" '
                'font-size="18" font-weight="600" font-family="Segoe UI, Arial, sans-serif">'
                "No sessions recorded yet</text>",
                f'<text x="{width / 2:.2f}" y="{height / 2 + 18:.2f}" text-anchor="middle" fill="#94a3b8" '
                'font-size="12" font-family="Segoe UI, Arial, sans-serif">'
                "Complete a practice session to see the graph.</text>",
                "</svg>",
            ]
        )
        return "".join(svg_parts)

    count = len(timeline)
    x_step = chart_width / (count - 1) if count > 1 else 0
    if count == 1:
        x_positions = [margin_left + (chart_width / 2)]
    else:
        x_positions = [margin_left + (x_step * index) for index in range(count)]

    points: list[tuple[float, float]] = []
    x_labels: list[str] = []

    for index, item in enumerate(timeline):
        score = _safe_score(item.get("confidence_score", 0))
        x = x_positions[index]
        y = margin_top + chart_height - (score / 100) * chart_height
        points.append((x, y))
        x_labels.append(_format_date_label(item.get("date"), f"S{index + 1}"))

    line_path = "M " + " L ".join(f"{x:.2f} {y:.2f}" for x, y in points)
    area_path = (
        line_path
        + f" L {points[-1][0]:.2f} {chart_bottom:.2f}"
        + f" L {points[0][0]:.2f} {chart_bottom:.2f} Z"
    )

    svg_parts.extend(
        [
            f'<path d="{area_path}" fill="url(#progressFill)" />',
            f'<path d="{line_path}" fill="none" stroke="#60a5fa" stroke-width="4" '
            'stroke-linecap="round" stroke-linejoin="round" />',
        ]
    )

    max_labels = 6
    if count <= max_labels:
        label_indices = list(range(count))
    else:
        spread = count - 1
        label_indices = sorted(
            {
                round((slot * spread) / (max_labels - 1))
                for slot in range(max_labels)
            }
        )

    for index in label_indices:
        x = x_positions[index]
        label = escape(x_labels[index])
        svg_parts.append(
            f'<text x="{x:.2f}" y="{height - 24}" text-anchor="middle" fill="#94a3b8" '
            'font-size="11" font-family="Segoe UI, Arial, sans-serif">'
            f"{label}</text>"
        )

    for index, item in enumerate(timeline):
        x, y = points[index]
        score = int(round(_safe_score(item.get("confidence_score", 0))))
        topic = escape(str(item.get("topic") or "Practice Session"))
        date_label = escape(_format_date_label(item.get("date"), f"Session {index + 1}"))
        svg_parts.extend(
            [
                f'<circle cx="{x:.2f}" cy="{y:.2f}" r="6" fill="#0f172a" stroke="#93c5fd" stroke-width="3">',
                f"<title>{topic}: {score}% on {date_label}</title>",
                "</circle>",
            ]
        )

    svg_parts.append("</svg>")
    return "".join(svg_parts)
